layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
     - PuckJs
     
mech-projects:
  - name: Airship
    image_url: /assets/img/Blimp.jpg
    description: Remote-controlled lighter-than-air vehicle

  - name: Stewart Platform
    image_url: /assets/img/Stewart.png
    description: 6 DOF control of a hydraulic platform
  
  - name: Rocketry Oxidizer Tank
    image_url: /assets/img/OxTank.jpeg
    description: CNC machined nitrous oxide tank designed to handle 1500psi
  
  - name: Automated Test Jig
    image_url: /assets/img/ReliabilityJig.jpg
    description: Linear stage automated reliability tester

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
    linkedin: stefan-martin

#topics:
 # - name: FEA

  #- name: Fluid Mechanics