layout: sidebar
style: dark

collections:
  mech:
    output: true

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
     - PuckJs
     
mech-projects:
  - name: Airship
    image_url: assets/img/Blimp.jpg
    url: mech/Blimp.html
    description: Remote controlled lighter-than-air vehicle

  - name: Stewart Platform
    image_url: assets/img/pureY.jpg
    url: mech/Stewart.html
    description: Servo controlled 6 DOF platform
  
  - name: Rocketry Oxidizer Tank
    image_url: assets/img/OxTank.jpeg
    url: mech/oxTank.html
    description: Weight optimized nitrous oxide tank designed to handle 1500psi
  
  - name: Automated Test Jig
    image_url: assets/img/ReliabilityJig.jpg
    url: mech/Reliability.html
    description: Arduino-controlled automated reliability tester which ran over 20,000 cycles

  - name: Daft Punk helmet
    image_url: assets/img/DaftPunk.jpg
    url: mech/DaftPunk.html
    description: 3D printed on the Form2 with a thermoformed visor
    

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
    linkedin: stefan-martin

#topics:
 # - name: FEA

  #- name: Fluid Mechanics